// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Extensions.PostgreSql.Tests.Common;

namespace Microsoft.Azure.WebJobs.Extensions.PostgreSql.Tests.Integration
{

    /// <summary>
    /// This class makes sure that the output binding works when the order of the properties in the POCO is different than the order of the columns in the PostgreSql table.
    /// </summary>
    public static class AddProductDifferentColumnOrder
    {
        /// <summary>
        /// This shows an example of a PostgreSQL Output binding where the target table has a default primary key and the column is not included in the output object. The order of the
        /// properties in the POCO is different from the order of the columns in the table. A new row will
        /// be inserted and the pk will be generated by the engine.
        /// </summary>
        /// <param name="req">The original request that triggered the function</param>
        /// <param name="output">The created ProductDifferentColumnOrder object</param>
        /// <returns>The CreatedResult containing the new object that was inserted</returns>
        [FunctionName("AddProductDifferentColumnOrder")]
        public static IActionResult Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "addproductdifferentcolumnorder")]
            HttpRequest req,
            [PostgreSql("Products", "PostgreSqlConnectionString")] out ProductDifferentColumnOrder output)
        {
            output = new ProductDifferentColumnOrder
            {
                Cost = 100,
                Name = "test"
            };
            return new CreatedResult($"/api/addproductdifferentcolumnorder", output);
        }
    }
}