CREATE TABLE ProductsColumnTypes (
    "ProductId" serial PRIMARY KEY,
    "Bigint" BIGINT,
    "Bigserial" BIGSERIAL,
    "Bit" BIT(1),
    "BitVarying" BIT VARYING(100),
    "Boolean" BOOLEAN,
    "Bytea" BYTEA,
    "Character" CHARACTER(100),
    "CharacterVarying" CHARACTER VARYING(100),
    "Date" DATE,
    "DoublePrecision" DOUBLE PRECISION,
    "Integer" INTEGER,
    "Interval" INTERVAL,
    "Json" JSON,
    "Jsonb" JSONB,
    "Numeric" NUMERIC(5, 2),
    "Real" REAL,
    "Smallint" SMALLINT,
    "Smallserial" SMALLSERIAL,
    "Serial" SERIAL,
    "Text" TEXT,
    "Time" TIME,
    "TimeWithTimeZone" TIME WITH TIME ZONE,
    "Timestamp" TIMESTAMP,
    "TimestampWithTimeZone" TIMESTAMP WITH TIME ZONE,
    "Uuid" UUID
);