// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

/**
 * This shows an example of a PostgreSQL Output binding where the target table has a default primary key and the column is not included in the output object. The order of the
 * properties in the POCO is different from the order of the columns in the table. A new row will
 * be inserted and the pk will be generated by the engine.
 */
module.exports = async function (context, req) {
  context.bindings.product = {
    Cost: 100,
    Name: "test",
  };

  return {
    status: 201,
    body: context.bindings.product,
  };
};
